<?php
//include_once("db_connection.php");
//include("qry/Query.php");
?>
<?php include("header.php"); ?>
<div id="mainContDisp" class="container playGames homePlayGames" style="margin-top:20px;margin-bottom:70px;">  
<form name="frmRegister" id="frmRegister" class="" method="post" enctype="multipart/form-data" >
  <div class="row">
    <div class="col-lg-12">
	<h1 style="margin:0 0 10px;  border: none;border-bottom: 2px solid #eaeaea;text-align: center;"><span style="padding-bottom:5px;">Privacy Policy</span> </h1>
	 </div></div>
	 
	 <div class="row">
	  <div class="innerContainer">
        	<div class="privacy">
			<h3>LAST UPDATED: 30/12/2019</h3>
<h3>To view our practices regarding children/student users, <a href="#Children_policy" style="color:#92278f;">click here</a> .</h3>

            	<p>SkillAngels<sup>TM</sup> is conceived by Edsix Brain Lab Pvt Ltd.<sup>&reg;</sup> ("Edsix Brain Lab Pvt Ltd <sup>&reg;</sup>", "Company", "we", "us" or "our"), we value your privacy and we ensure that we take utmost care with regards to your personal data. Our Privacy Policy is applicable to the treatment of personally identifiable information ("Personal Information") that we gather while you're accessing <a href="http://skillangels.com/" target="_blank" style="color:#92278f;" >www.skillangels.com</a> or sub-urls under www.skillangels.com (the "Site") and/or the SkillAngels<sup>TM</sup> online service (“Service”). This policy is not applicable to individuals and processes that we do not employ control or manage. BY ACCESSING THE SITE, YOU SIGNIFY AND WARRANT THAT YOU HAVE READ AND UNDERSTOOD AND FULLY AGREE TO THE TERMS OF OUR PRIVACY POLICY. IF YOU DO NOT AGREE OR UNDERSTAND THIS PRIVACY POLICY, YOU MUST IMMEDIATELY LEAVE THE SITE.</p>

                <h3>We collect information that helps us to customize and adapt our services. We collect different types of information as mentioned below from our customers.</h3>
                <p>THESE TERMS AND CONDITIONS IN THE END USER AGREEMENT ARE GOVERNED IN ACCORDANCE WITH THE LAWS OF INDIA. ANY DISPUTE SHALL BE SUBJECT TO THE EXCLUSIVE JURISDICTION OF COURTS IN CHENNAI ONLY.</p>
                <ul>
	<li><h3>User Provided Information:</h3><p>In order for you to use some of the Site's Services, you will be asked to provide to us with certain Personal Information. Personal Data includes, but is not restricted to: (1) "Contact Information" (such as your name, company name, mailing address, and e-mail address etc.); (2) "Financials" (such as your account or credit card number etc.); and (3) "Demographics"(such as you pin code, age, etc.) that are linked to your Personal Information. Whenever you are required to furnish Personal Information, you will be asked to provide it. Our website will not gather it secretly. In any case, you are not obliged to provide Personal data, however, not providing your information when requested may stop you from being able to use our Site's Services.</p></li>
	<li><h3>Information Automatically Collected by us:</h3><p>We may collect and store certain types of information whenever you use our web site or services. The Company automatically obtains and registers informationfrom your browser in our server logs, including your IP address, Company cookie information, the page requested, game and training programs data. Our service automatically collects information about usage like the number of visitors to our site; frequency to identify how many users and traffic was seen in our site. We aggregate this data and use it more for statistical analysis and not in a way that will identify you personally.</p></li>
	<li id="cookie"><h3>Cookies:</h3><p>Similar to many websites, we use cookies and other standard web technologies to collect information from end users for our own use. Cookies can be defined as alphanumeric identifiers that get transferred to your computer's hard drive through your browser to aid our systems to recognize your browser and give us information and metrics about site visits and number of users for our site.</p><p>All popular browsers have an option to turn off the cookie feature, which will prevent your browser from accepting new cookies and also allowing you to customize the acceptance of cookies. It is recommended that you keep this setting turned on to fully experience the site and its features. If you choose to turn off the cookies feature, you will assume full responsibility for any resulting loss of site functionality.</p></li>
	<li><h3>Usage of Personal Information:</h3><p>The information collected from you is used to authenticate your credentials and visits, and also to send you information about our products and services. If you have subscribed to receive marketing information about our products or services, it will be customized to your preferences. The information we collect also is used by us to improve our site, contents, games and training mechanisms, and to track student performance and learning progress for reference by the student’s parent or school teacher.</p>
<p>The data collected will also be aggregated for us to conduct research in collaboration with external researchers and validate effectiveness of our program from time to time.</p></li>
	<li><h3>Third party information disclosure - limited disclosure:</h3><p>We value your personal data and see that our customers privacy is kept utmost confidential. Your personal information will not be not shared to external or third parties for their own direct marketing or usage. Any sharing of your personal information happens only in one of the manners explained below:</p><p>
(1) For the purpose of sharing your information with third party service providers or companies who we hire to do tasks specifically on our behalf. For example, Payment Gateway vendors (currently ccAvenue) to process account, credit card information securely over the web. No information beyond what is reasonably needed to provide the Service would be captured from our customers by us or a vendor on our behalf.</p><p>
(2) We may also disclose Personal Information when required to do so by law, or in response to a court order, or other legal mechanism, or when we believe, at our sole discretion, that disclosure is reasonably necessary to protect the property or rights of the Company, third parties or the public at large.</p><p>
(3) We reserve the right to sell, transfer or otherwise share some or all of our assets, including information provided by you, in connection with a merger, reorganization or sale of some or all of our assets or in the event of bankruptcy. In any such event, personally identifiable and other information may be one of the assets transferred.We will post notice before personal information is transferred and becomes subject to a different privacy policy, and if necessary, gain your prior approval or the approval of a parent, school, or other legal guardian.</p><p>
You hereby consent to our sharing of Personal Information for the above purposes.</p></li>
	<li><h3>Personal Security:</h3><p>We have put in place reasonable security protocols and measures in place to prevent unauthorized access, usage and modifications. Our systems have incorporated measures such as SSL encryption, firewalls and antivirus software for data protection. These will be updated on a regular basis to ensure your Personal Information is protected.</p></li>
	<li><h3>Choice Preference:</h3><p>The usage of the site to register and gain access to the site is not mandatory for the user. If the user chooses to do the same, all personal data and information will be governed by this privacy policy. You are not required to register to gain access to many areas of the Site. If you use the Site's personalised services, however, we will treat your Personal Information as described in this Privacy Policy.</p></li>
	<li id="Children_policy"><h3>Children’s privacy policy:</h3><p>Edsix Brain Lab values the importance of safeguarding children's privacy in an online space and strives to comply with laws such as the U.S. Children’s Online Privacy Protection Act (“COPPA”). Our website and the Service are designed in in a way such that any video, audio or content is child friendly and can be supervised or monitored by the parent. The targeted user group is any individual or student above 3 years old.</p><p>
 This monetary transaction is used as permission to grant young children/students access to the Service, to capture and upload certain information about such users (such as name, grade level, school name, address) and to authorize our ability to collect certain information about their use of the Service, including statistics related to game play and learning progress. This information may be linked back to a parent account, or individualstudent names and profiles under a school account. The Service does not provide a means for children/students to chat or message each other, or to post personal information publicly.</p><p>
Parents and schools may access their child’s/students’ data at any time after logging in to their account. They may also request at any time that we stop collecting or further using their child’s/students’ personal information, or that we delete such personal information from our records. Doing so, however, may result in the termination of your account and the inability to access the Service, without refund.</p><p>
To learn more about COPPA, you may reference this simple one-page informational guide from the kidSAFE Seal Program: <a href="http://www.kidsafeseal.com/knowaboutcoppa.html" target="_blank"  style="color:#92278f;">www.kidsafeseal.com/knowaboutcoppa.html</a>.</p></li>
	<li><h3>Third party links:</h3><p>Our website may contain links to third party sites or software. We don't own or take responsibility for the content or information provided by them. Please carefully review their respective privacy policies.</p></li>
	<li><h3>Privacy Policy Changes:</h3><p>Our Privacy Policy may be updated or modified over a period of time.  We will indicate any such changes at the privacy policy link in our home menu. At each point of time, you should ensure that you check the "Last Updated" date of this privacy policy (located at the top), and review any changes since you last accessed the Site. Such changes are effective immediately from the Last Updated date shown above. Unless specified otherwise, any revised Privacy Policy will apply only to information collected after the effective date of such revised Privacy Policy, and not to information collected under any earlier Privacy Policy. If we were to make material changes to the handling of personal information collected under an earlier Privacy Policy, we would give you prominent notice and seek your prior consent, or the prior consent of a parent, school, or other legal guardian.</p></li>
	<li><h3>Queries / Concerns:</h3><p>Any queries/clarifications or concerns regarding this privacy policy are welcomed by us. Please send an email to <a href="mailto:angel@skillangels.com" style="color:#92278f;">angel@skillangels.com</a>.</p></li>
</ul>
            </div>
        </div>
	 
	 </div>
	 <br/>
   

    
   
 </form>
</div>
<?php include("footer.php"); ?>